In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/dhanushnarayananr/credit-card-fraud/card_transdata.csv


In [2]:
df = pd.read_csv('/kaggle/input/datasets/dhanushnarayananr/credit-card-fraud/card_transdata.csv')
df.head(3)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0


In [3]:
df['fraud'].unique()

array([0., 1.])

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
y = df['fraud']
x = df.drop('fraud',axis=1)

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.9,random_state=42)

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
log = LogisticRegression()
model = log.fit(x_train,y_train)
model.score(x_test,y_test)

0.95866

In [9]:
df['fraud'].value_counts()

fraud
0.0    912597
1.0     87403
Name: count, dtype: int64

In [10]:
from sklearn.metrics import confusion_matrix

In [11]:
y_pred = model.predict(x_test)

In [12]:
confusion_matrix(y_test,y_pred)

array([[90664,   633],
       [ 3501,  5202]])

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [14]:
tree = DecisionTreeClassifier()
model_tree = tree.fit(x_train,y_train)
model_tree.score(x_test,y_test)

1.0

In [15]:
y_tree_pred = model_tree.predict(x_test)

In [16]:
confusion_matrix(y_test,y_tree_pred)

array([[91297,     0],
       [    0,  8703]])

In [17]:
a = pd.DataFrame()
a['true']=y_test
a['pred']=y_pred

In [18]:
a[a['true']==1].value_counts()

true  pred
1.0   1.0     5202
      0.0     3501
Name: count, dtype: int64